### ISSUE TITLE
Link "Factory-based middleware activation with a third-party container" is broken

### ISSUE THREAD

**Issue by oacostam** [aspnet/Docs.es-es#8]
The link at the end of the docuement "Factory-based middleware activation with a third-party container" is broken, it points to xref:fundamentals/middleware/extensibility-third-party-container. Maybe the right link is https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility-third-party-container

**Comment by CeciAc** [comment]
Thank you for your feedback
We found no broken links in the page you mention, could you please provide more details
- Webpare URL were you spot the error
- Text of the link which doesn't work
Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @oacostam 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/aspnet/Docs/issues/5740

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
